# Generated by Django 4.2.30 on 2026-07-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoCeleryResultsChordcounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('sub_tasks', models.TextField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'django_celery_results_chordcounter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoCeleryResultsGroupresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField()),
                ('date_done', models.DateTimeField()),
                ('content_type', models.CharField(max_length=128)),
                ('content_encoding', models.CharField(max_length=64)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_celery_results_groupresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoCeleryResultsTaskresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=128)),
                ('content_encoding', models.CharField(max_length=64)),
                ('result', models.TextField(blank=True, null=True)),
                ('date_done', models.DateTimeField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('task_args', models.TextField(blank=True, null=True)),
                ('task_kwargs', models.TextField(blank=True, null=True)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('worker', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField()),
                ('periodic_task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_celery_results_taskresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('album_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(blank=True, max_length=200, null=True)),
                ('album_image', models.CharField(blank=True, max_length=255, null=True)),
                ('image_square', models.TextField(blank=True, null=True)),
                ('image_large_square', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '앨범',
                'verbose_name_plural': '2️⃣ 🎵 MUSIC - 앨범',
                'db_table': 'albums',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('artist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_image', models.TextField(blank=True, null=True)),
                ('image_large_circle', models.TextField(blank=True, null=True)),
                ('image_small_circle', models.TextField(blank=True, null=True)),
                ('image_square', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '아티스트',
                'verbose_name_plural': '2️⃣ 🎵 MUSIC - 아티스트',
                'db_table': 'artists',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '장르',
                'verbose_name_plural': '2️⃣ 🎵 MUSIC - 장르',
                'db_table': 'genres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('music_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=200)),
                ('is_ai', models.BooleanField(blank=True, null=True)),
                ('audio_url', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('valence', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('arousal', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('itunes_id', models.BigIntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.albums')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.artists')),
            ],
            options={
                'verbose_name': '음악',
                'verbose_name_plural': '2️⃣ 🎵 MUSIC - 음악',
                'db_table': 'music',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('tag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag_key', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '2️⃣ 🎵 MUSIC - 태그',
                'db_table': 'tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '1️⃣ 👤 USER - 사용자',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlayLogs',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('play_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField()),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.users')),
            ],
            options={
                'verbose_name': '재생 기록',
                'verbose_name_plural': '4️⃣ 📊 ANALYTICS - 재생 기록',
                'db_table': 'play_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('visibility', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.users')),
            ],
            options={
                'verbose_name': '플레이리스트',
                'verbose_name_plural': '3️⃣ 📝 PLAYLIST - 플레이리스트',
                'db_table': 'playlists',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaylistLikes',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.playlists')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.users')),
            ],
            options={
                'verbose_name': '플레이리스트 좋아요',
                'verbose_name_plural': '3️⃣ 📝 PLAYLIST - 플레이리스트 좋아요',
                'db_table': 'playlist_likes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaylistItems',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.music')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.playlists')),
            ],
            options={
                'verbose_name': '플레이리스트 항목',
                'verbose_name_plural': '3️⃣ 📝 PLAYLIST - 플레이리스트 항목',
                'db_table': 'playlist_items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MusicLikes',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.music')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.users')),
            ],
            options={
                'verbose_name': '음악 좋아요',
                'verbose_name_plural': '4️⃣ 📊 ANALYTICS - 음악 좋아요',
                'db_table': 'music_likes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='music',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.users'),
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('chart_id', models.AutoField(primary_key=True, serialize=False)),
                ('play_count', models.IntegerField(blank=True, null=True)),
                ('chart_date', models.DateTimeField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, choices=[('realtime', '실시간 차트'), ('daily', '일일 차트'), ('ai', 'AI 차트')], null=True)),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.music')),
            ],
            options={
                'verbose_name': '차트',
                'verbose_name_plural': '4️⃣ 📊 ANALYTICS - 차트',
                'db_table': 'charts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.artists'),
        ),
        migrations.CreateModel(
            name='AlbumLikes',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.albums')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.users')),
            ],
            options={
                'verbose_name': '앨범 좋아요',
                'verbose_name_plural': '4️⃣ 📊 ANALYTICS - 앨범 좋아요',
                'db_table': 'album_likes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('aiinfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('input_prompt', models.CharField(blank=True, max_length=500, null=True)),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.music')),
            ],
            options={
                'verbose_name': 'AI 정보',
                'verbose_name_plural': '5️⃣ 🤖 AI - AI 정보',
                'db_table': 'ai_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersGenre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.users')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.genres')),
            ],
            options={
                'verbose_name': '사용자 선호 장르',
                'verbose_name_plural': '1️⃣ 👤 USER - 사용자 선호 장르',
                'db_table': 'users_genre',
                'managed': True,
                'unique_together': {('user', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='MusicTags',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.music')),
                ('score', models.FloatField(blank=True, default=0.0, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.tags')),
            ],
            options={
                'verbose_name': '음악 태그',
                'verbose_name_plural': '2️⃣ 🎵 MUSIC - 음악 태그',
                'db_table': 'music_tags',
                'managed': True,
                'unique_together': {('music', 'tag')},
            },
        ),
    ]
