# Generated by Django 4.2.30 on 2026-07-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='albums',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albums',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artists',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='music',
            name='isrc',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_type',
            field=models.CharField(default='mood', max_length=16),
        ),
        # music_tags PK 교체: 기존 music_id 단일 PK를 surrogate music_tag_id로 대체한다.
        # 로컬 DB의 music_tags는 데이터가 없으므로 (시드 30곡은 태그 없음) 안전하게 수행 가능.
        # 순서 중요: 먼저 기존 PK(music 필드)를 해제한 뒤에 새 PK 컬럼을 추가해야
        # Postgres가 "multiple primary keys for table" 오류를 내지 않는다.
        migrations.AlterField(
            model_name='musictags',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.music'),
        ),
        migrations.AddField(
            model_name='musictags',
            name='music_tag_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MusicSimilar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('music_similar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('match', models.FloatField(default=0.0)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_from', to='music.music')),
                ('similar_music', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_to', to='music.music')),
            ],
            options={
                'verbose_name': '유사 곡',
                'verbose_name_plural': '2️⃣ 🎵 MUSIC - 유사 곡',
                'db_table': 'music_similar',
                'managed': True,
                'unique_together': {('music', 'similar_music')},
            },
        ),
        migrations.CreateModel(
            name='ArtistGenres',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('artist_genre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.artists')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.genres')),
            ],
            options={
                'verbose_name': '아티스트 장르',
                'verbose_name_plural': '2️⃣ 🎵 MUSIC - 아티스트 장르',
                'db_table': 'artist_genres',
                'managed': True,
                'unique_together': {('artist', 'genre')},
            },
        ),
    ]
