# Generated by Django 4.2.30 on 2026-07-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_lyrics_albums_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='artists',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='music',
            name='spotify_id',
        ),
        migrations.AddField(
            model_name='albums',
            name='deezer_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artists',
            name='deezer_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='music',
            name='deezer_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
