# Generated by Django 4.2.30 on 2026-07-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_albums_spotify_id_remove_artists_spotify_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
