# Generated by Django 4.2.30 on 2026-07-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_generationjob_active_constraint'),
        ('music', '0004_alter_music_audio_url'),
    ]

    operations = [
    ]
