# Generated by Django 4.2.30 on 2026-07-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_merge_20260710_1919'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='generationjob',
            name='uniq_active_generation_per_user',
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='phase',
            field=models.CharField(choices=[('converting', 'Converting'), ('generating', 'Generating'), ('preparing_audio', 'Preparing audio'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='generationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('phase__in', ['converting', 'generating', 'preparing_audio'])), fields=('user',), name='uniq_active_generation_per_user'),
        ),
    ]
